### ISSUE TITLE
Invalid MAC of handshake, dropping packet from

### ISSUE THREAD

**Issue by wpresources** [micahmo/WgServerforWindows#15] opened 2021-11-30 01:39 UTC
Steps I did WireGuard Server For Windows in VPS
1.successfully run all requests
https://ibb.co/Fz1vmZf
2.
Infor Server Configuration https://ibb.co/bbH36sD
Export Configuration File => vpnFile.conf  https://ibb.co/CWZ5bgr
3.I opened port 51820 on Firewall
4.Use vpnFile.conf on another computer
https://ibb.co/zmrw5sz
5.Wireguard always notices on the log "invalid MAC of handshake, dropping packet from"
https://ibb.co/HTsw1Ht
=>It makes my connected computer unable to access the network
=>I'm a newbie with no experience.I don't know what step I'm missing or where I'm going wrong. Please help me

**Comment by micahmo** [comment] 2021-11-30 12:23
Hi @wpresources, this sounds like more a WireGuard problem than a WS4W problem, but there are a few things you can check.

Does this values in the registry get updated?
![image](https://user-images.githubusercontent.com/7417301/144045677-b48d228a-30f2-4b43-9675-980959c6a441.png)

Do you see anything if you open Logs from WS4W?

When the client is trying to connect, can you ping it from the server? (10.243.0.2)

In that Invalid MAC error messages, is the source IP address (103.127.207.199) the expected public IP address of the client?

According to everything I'm seeing online, that error is usually associated with a bad key on the client side, but if you've used WS4W to generate all the keys (and based on your screenshots), everything should be correct.

**Comment by wpresources** [comment] 2021-11-30 17:16
This is the vps address where i am trying to create a vpn server (185.80.234.52   passServer!)
the ip address i check the ip check page is 118.69.3.196 (118.69.3.196 passClient!) but the error message is ip 103.127.207.199.
Please take a moment to help me check it

**Comment by micahmo** [comment] 2021-11-30 22:43
Hi @wpresources, I connected and took a look. Your configuration looks fine, but I was also unable to connect to your server from my client.

I'm afraid the problem is related to port forwarding. I understand you're using a VPS, and you have unblocked the port in your machine's firewall. However, your VPS may only route certain ports (like 3389 for RDP) to your VM, whereas other ports (like 51820 for WireGuard) may be blocked.

I used this website to test the open ports on your VMs public IP: https://www.yougetsignal.com/tools/open-ports/

Sure enough, seems like the WireGuard port is closed.

![image](https://user-images.githubusercontent.com/7417301/144139842-5e23b3bd-5218-423f-9431-ef0f09587f57.png)

![image](https://user-images.githubusercontent.com/7417301/144139840-3bcd8837-4993-4e70-8bd9-bc1bca86b80c.png)

Maybe you can open it in the VPS configuration?

**Comment by wpresources** [comment] 2021-11-30 23:28
I asked the vps provider they said
`In order for the port to be displayed open during an external check, it is necessary that the port is "listened to" by some service or program that must be running at that time and configured to work with this particular port.
`
Bypass ip vps try working on my computer 118.69.3.196.I opened two ports 3389 and 51820 but only 3389 works

**Comment by micahmo** [comment] 2021-12-01 01:42
Yeah you're right, that port scanner is not a good test. It also doesn't show the WireGuard port open on my server that currently works.

I just remembered that WireGuard uses UDP protocol. Can you verify that your VPS forwards UDP?

While I was connected to your server, I checked the logs in WS4W. They don't show any incoming connection from the client. I think the "Invalid MAC of handshake" from the WireGuard logs are not related to this case (like you said, the origin IP was different from your (and my) client machine). Seems like the client cannot establish the connection at all. 

I only have a couple more suggestions:
1. Use `netstat` or [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) on the server to verify that WireGuard is listening on the port. This is mine (I use `51821`):
   ![image](https://user-images.githubusercontent.com/7417301/144155351-6904fcd7-efa9-4e6c-aa1d-6736018e82ce.png)
2. Use [Wireshark](https://www.wireshark.org/) on the server with a filter like `udp.port eq 51820`. Here is an example from my server. Notice I get a handshake request received, handshake response sent, and then immediately traffic starts flowing.
   ![image](https://user-images.githubusercontent.com/7417301/144156210-f0a4ef60-edbf-4e2f-9a5f-b9bfc1516eec.png)
3. Maybe try OpenVPN (they have a [guide](https://community.openvpn.net/openvpn/wiki/Easy_Windows_Guide?__cf_chl_jschl_tk__=EXYh7RSjoOFgZIdqg_PDTdi.oMjFFFfU.18.FBVSpQc-1638321823-0-gaNycGzNBz0) for configuring a server on Windows). If that works, you can use it instead of WireGuard. If not, then there is a general problem with the networking of the VPS machine.

Sorry I don't have more to offer! I am not really a WireGuard expert when it goes beyond a fairly trivial setup.

**Comment by wpresources** [comment] 2021-12-01 01:49
Due to some error I am resetting my computer, I will try your latest way
You helped me understand a lot more about WireGuard and VPN, very easy to understand

**Comment by wpresources** [comment] 2021-12-01 19:38
Hi I would like to ask for the same Remote Address and Remote Port information as you?
https://imgur.com/a/Rhf613G
Set a name when using WS4W to name the item Server Configuration and Configure Client. Or when naming wireguard https://ibb.co/zmrw5sz
=>Is it possible to set optional or mandatory according to the name structure?

**Comment by micahmo** [comment] 2021-12-02 12:04
> Hi I would like to ask for the same Remote Address and Remote Port information as you?
https://imgur.com/a/Rhf613G

Yep, that looks good to me. Your WireGuard process is listening to port 51820 on all interfaces with both IPv4 and IPv6.

> Is it possible to set optional or mandatory according to the name structure? Because in the manual page the item your name has blurred

No, the name doesn't matter, it's just for your convenience. In the WireGuard config file, it gets added as a comment, but, as you discovered, the value is ignored when you import the WireGuard configuration file into the client application.

May I ask what VPS you are using? If I have time, I could try setting up my own system to do some troubleshooting. But again, this is very likely outside the scope of my WireGuard knowledge.

**Comment by wpresources** [comment] 2021-12-02 12:53
Yes i am using vps at https://zomro.net/vds.html.With your knowledge, I believe I will be able to fix it. When I successfully fix it, I will let you know :D

**Comment by wpresources** [comment] 2021-12-03 12:50
If you are still interested or have some interest, I would like to talk about my findings
My problem comes from IP Address 10.253.0.1 according to related threads I found it's quite common ip
But
My IP Address is 192.168.1.247
Subnet mask 255.255.255.0
Default gateway 192.168.1.1
=> I'm sure that's the reason for the "package has unallowed src ip" error.
After I changed the above error did not exist, but I got another error "package has unallowed src ip" I think it is simpler. Maybe the client.conf or server.conf file configuration is not suitable

**Comment by wpresources** [comment] 2021-12-03 23:33
I believe my error is coming from Address.10.253.0.1 is a common ip but my ip is different
IP Address: 192.168.1.247
Subnet: 255.255.255.0
Default gateway 192.168.1.1
=> I believe it is the reason for "Invalid MAC of handshake, packet from".Currently I get the error "packet has unallowed src ip" maybe it comes from client.conf and server.conf config files

**Comment by micahmo** [comment] 2021-12-04 15:56
Keep in mind the network range for the WireGuard network must not conflict with your machine's network. It looks like your machine is using `192.168.1.0/24` (CIDR), and WireGuard is using `10.253.0.1/24`, so there should be no conflict there.

I know it seems counterintuitive that you want WireGuard on a separate network, but that's what the Network Sharing feature in Windows is for. It allows a request from one network to travel to the other. If both networks have the same IP range, things get messy.

**Comment by micahmo** [comment] 2021-12-04 21:30
Hey @wpresources, I finally had some time to try this out on a Zomro VPS. Believe it or not, WS4W worked right out of the box with no problems! I don't know why it would be any different than yours, but I followed all the basic steps in WS4W (except for "Persistent Internet Sharing", because I don't really care it it breaks after rebooting), then I exported the client config to my phone, connected to the WireGuard VPN, and I was on the Zomro network.

Here are some screenshots, but again, I didn't do any unusual configuration.

![image](https://user-images.githubusercontent.com/7417301/144724879-c4bdea5d-0158-459a-aec8-51e1438ecdd3.png)

![image](https://user-images.githubusercontent.com/7417301/144724936-6a08fdce-e8d0-4b9c-bf3b-0f5dece0b8fe.png)

![image](https://user-images.githubusercontent.com/7417301/144724962-a00880c5-a925-44c9-8a50-3e0932c9908b.png)

The most important part: I'm getting a handshake and data transfer from my client.

![image](https://user-images.githubusercontent.com/7417301/144724981-97c586b6-1c7e-4f9e-a5d8-2e6392602fa3.png)

From my phone I connected to the WireGuard VPN, and [whoismyisp.org](https://www.whoismyisp.org/) confirms I'm on the Zomro machine's network.

<img src="https://user-images.githubusercontent.com/7417301/144725016-c9237015-4f9b-4dfd-b281-b4b259761038.png" width=50% height=50%>

Let me know if you'd like me to share the VM credentials and/or WireGuard client info with you privately.

**Comment by micahmo** [comment] 2021-12-27 01:56
Hey @wpresources, I'm trying to clean up some old issues. Is there anything else I can do to help with this issue? As mentioned in my last comment, I signed up for a Zomro VPS and was able to get WS4W working right out of the box, so I don't think there's anything inherently wrong with that VPS. I'm still willing to share those credentials if you'd like to connect and take a look. Otherwise, I'm not sure what else I can do to help. Let me know!

**Comment by andrewhill93** [comment] 2022-05-02 22:32
I'm getting an issue kind of like this, except it happens each time I deactivate the server. Every time I deactivate the server, it changes the public keys of the clients and I have to reconfigure the VPN on my devices with the new config file. It gives me the same "Invalid MAC, Dropping packet" error. I don't know if I just didn't read the documentation properly or what, but seems crazy that each time I shut off the server so I can restart my physical machine, it changes the public key. Do you know of a what to stop the keys from changing?

**Comment by micahmo** [comment] 2023-02-10 19:08
As this issue has not had any activity in over a year, I am going to close it. Of course, please feel free to reopen at any time.

**Closed by micahmo** 2023-02-10 19:08 UTC
Labels: awaiting-feedback, wireguard-question
