### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by timbolin** [micahmo/WgServerforWindows#93] opened 2023-02-07 04:52 UTC
this little tool made my life SO much easier. how can i send a donation as a token of my appreciation?

**Comment by micahmo** [comment] 2023-02-07 14:43
Dupe of #32 😄

In all seriousness, that's very kind of you. Since I've gotten multiple requests to do this, I have added a "Buy Me a Coffee" link to my [profile](https://github.com/micahmo). Please never feel obligated to donate! I maintain this project in my free time and can't promise any support. 😊

**Closed by micahmo** 2023-02-07 14:43 UTC
